name: Release

on:
  push:
    tags:
      - '**'

permissions:
  contents: read

jobs:
  prepare_release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build and push container image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: push
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=out

      - name: Compress artifacts and generate checksums
        run: |
          for i in dev-env-update-hosts-*; do
            gzip -9n "${i}";
            sha256sum "${i}.gz" | awk '{print $1}' > "${i}.gz.sum";
          done
        working-directory: out

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: |
            out/dev-env-update-hosts-*

      - name: Generate provenance file
        run: |
          jq .dsseEnvelope "${{ steps.attest.outputs.bundle-path }}" > out/dev-env-update-hosts.intoto.jsonl

      - name: Create a release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          generate_release_notes: true
          files: |
            out/*.gz
            out/*.gz.sum
            out/dev-env-update-hosts.intoto.jsonl
